BEGIN;
--
-- Create model Task
--
CREATE TABLE "todo_task" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(255) NOT NULL, "description" text NOT NULL, "scheduled_time" timestamp with time zone NULL, "is_completed" boolean NOT NULL, "is_recurring" boolean NOT NULL, "recurrence_pattern" varchar(255) NOT NULL, "task_type" varchar(100) NOT NULL, "device_type" varchar(100) NOT NULL, "action" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "user_id" integer NOT NULL);
ALTER TABLE "todo_task" ADD CONSTRAINT "todo_task_user_id_69f329a5_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "todo_task_user_id_69f329a5" ON "todo_task" ("user_id");
COMMIT;


BEGIN;
--
-- Create model Category
--
CREATE TABLE "todo_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL UNIQUE);
--
-- Add field category to task
--
ALTER TABLE "todo_task" ADD COLUMN "category_id" bigint NULL CONSTRAINT "todo_task_category_id_fb0c0926_fk_todo_category_id" REFERENCES "todo_category"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "todo_task_category_id_fb0c0926_fk_todo_category_id" IMMEDIATE;
CREATE INDEX "todo_category_name_124c74fd_like" ON "todo_category" ("name" varchar_pattern_ops);
CREATE INDEX "todo_task_category_id_fb0c0926" ON "todo_task" ("category_id");
COMMIT;


BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;


BEGIN;
--
-- Remove field action from task
--
ALTER TABLE "todo_task" DROP COLUMN "action" CASCADE;
--
-- Remove field device_type from task
--
ALTER TABLE "todo_task" DROP COLUMN "device_type" CASCADE;
--
-- Remove field is_recurring from task
--
ALTER TABLE "todo_task" DROP COLUMN "is_recurring" CASCADE;
--
-- Remove field recurrence_pattern from task
--
ALTER TABLE "todo_task" DROP COLUMN "recurrence_pattern" CASCADE;
--
-- Remove field task_type from task
--
ALTER TABLE "todo_task" DROP COLUMN "task_type" CASCADE;
COMMIT;


BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;


BEGIN;
--
-- Add field slug to task
--
ALTER TABLE "todo_task" ADD COLUMN "slug" varchar(200) NULL UNIQUE;
CREATE INDEX "todo_task_slug_e7a5bf53_like" ON "todo_task" ("slug" varchar_pattern_ops);
COMMIT;


BEGIN;
--
-- Alter field slug on task
--
-- (no-op)
--
-- Alter field title on task
--
ALTER TABLE "todo_task" ADD CONSTRAINT "todo_task_title_fe9014fc_uniq" UNIQUE ("title");
CREATE INDEX "todo_task_title_fe9014fc_like" ON "todo_task" ("title" varchar_pattern_ops);
COMMIT;


BEGIN;
--
-- Add field recurrence_days to task
--
ALTER TABLE "todo_task" ADD COLUMN "recurrence_days" varchar(20) DEFAULT '' NOT NULL;
ALTER TABLE "todo_task" ALTER COLUMN "recurrence_days" DROP DEFAULT;
--
-- Add field recurrence_time to task
--
ALTER TABLE "todo_task" ADD COLUMN "recurrence_time" time NULL;
--
-- Add field task_type to task
--
ALTER TABLE "todo_task" ADD COLUMN "task_type" varchar(20) DEFAULT 'user' NOT NULL;
ALTER TABLE "todo_task" ALTER COLUMN "task_type" DROP DEFAULT;
COMMIT;


BEGIN;
--
-- Add field last_completed_date to task
--
ALTER TABLE "todo_task" ADD COLUMN "last_completed_date" date NULL;
COMMIT;


BEGIN;
--
-- Create model Notification
--
CREATE TABLE "todo_notification" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "message" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "is_read" boolean NOT NULL, "user_id" integer NOT NULL);
ALTER TABLE "todo_notification" ADD CONSTRAINT "todo_notification_user_id_d5944080_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "todo_notification_user_id_d5944080" ON "todo_notification" ("user_id");
COMMIT;


