# Generated by Django 4.2.23 on 2025-07-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_default_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='action',
        ),
        migrations.RemoveField(
            model_name='task',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_pattern',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
    ]
