# Generated by Django 5.2.4 on 2025-07-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_task_slug_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_days',
            field=models.CharField(blank=True, help_text="Comma-separated days for automation (e.g. 'mon,tue,wed')", max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_time',
            field=models.TimeField(blank=True, help_text='Time of day for automation task recurrence', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('user', 'User Task'), ('automation', 'Home Automation')], default='user', max_length=20),
        ),
    ]
