# Generated by Django 5.2.4 on 2025-07-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_task_recurrence_days_task_recurrence_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_completed_date',
            field=models.DateField(blank=True, help_text='The last date this automation task was completed.', null=True),
        ),
    ]
